spring:
  application:
    name: Banchan

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-db:3305/banchan?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect

  profiles:
    active: oauth

jwt:
  secret: e13af114d471424d6c9f2b7d03c3e25e630f269fbb3587f35068cb7d253150f568812b114afd8fd6941a005cdcf64b8b8baec4ce9de512b6aaad9ba732c6eee4
  expiration: 1296000000

redis:
  host: redis-refresh-token
  port: 6379
  password: banchan201105

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

# Swagger Configuration
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

